import type { JurisdictionRule } from "../types";

/**
 * Deadline and filing-format rules, researched against primary rule text
 * (Cornell LII, official court/JPML sites) for the jurisdictions represented
 * in shared/mockData.ts. Not an exhaustive nationwide rule set — extend with
 * the same shape for additional courts.
 *
 * Entries with `days: 0` are filing-format references (page/word/font limits)
 * rather than countdown deadlines — UI code computing a deadline should filter
 * to `days > 0`; a rules-browser view can show all of them.
 */
export const JURISDICTION_RULES: JurisdictionRule[] = [
  {
    id: "frcp-12a1Ai",
    jurisdictionType: "federal",
    jurisdictionLabel: "Federal — all districts",
    citation: "FRCP 12(a)(1)(A)(i)",
    description: "Answer due after service of the summons and complaint.",
    triggerEvent: "Service of process",
    days: 21,
    dayType: "calendar",
    rollForward: true,
    source: "Fed. R. Civ. P. 12(a)(1)(A)(i); computation per Rule 6(a)",
  },
  {
    id: "frcp-12a1Aii",
    jurisdictionType: "federal",
    jurisdictionLabel: "Federal — all districts",
    citation: "FRCP 12(a)(1)(A)(ii)",
    description: "Answer due after defendant timely waives service under Rule 4(d) (domestic address; 90 days if the waiver request was sent abroad).",
    triggerEvent: "Rule 4(d) waiver request sent",
    days: 60,
    dayType: "calendar",
    rollForward: true,
    source: "Fed. R. Civ. P. 12(a)(1)(A)(ii)",
  },
  {
    id: "removal-1446b",
    jurisdictionType: "federal",
    jurisdictionLabel: "Federal — all districts",
    citation: "28 U.S.C. § 1446(b)(1)",
    description: "Deadline to remove a civil action from state to federal court (diversity-only removal under § 1446(b)(3) is barred more than one year after the action commenced, absent bad-faith).",
    triggerEvent: "Receipt of initial pleading",
    days: 30,
    dayType: "calendar",
    rollForward: true,
    source: "28 U.S.C. § 1446(b)(1); computation per Fed. R. Civ. P. 6(a)",
  },
  {
    id: "frcp-26a1",
    jurisdictionType: "federal",
    jurisdictionLabel: "Federal — all districts",
    citation: "FRCP 26(a)(1)(C)",
    description: "Initial disclosures due after the Rule 26(f) discovery conference, absent stipulation or court order (30 days from being served/joined for later-added parties).",
    triggerEvent: "Rule 26(f) conference",
    days: 14,
    dayType: "calendar",
    rollForward: true,
    source: "Fed. R. Civ. P. 26(a)(1)(C)",
  },
  {
    id: "frap-4a1A",
    jurisdictionType: "federal",
    jurisdictionLabel: "Federal — all districts",
    citation: "FRAP 4(a)(1)(A)",
    description: "Notice of appeal due after entry of the judgment or order appealed from (60 days if the United States or a federal officer/agency is a party). A timely Rule 50(b)/52(b)/59/60(b)-within-28-days motion resets the clock to the ruling on that motion.",
    triggerEvent: "Entry of judgment or order",
    days: 30,
    dayType: "calendar",
    rollForward: true,
    source: "Fed. R. App. P. 4(a)(1)(A), 4(a)(4)(A)",
  },
  {
    id: "jpml-6.2b",
    jurisdictionType: "jpml",
    jurisdictionLabel: "JPML — Conditional Transfer Order",
    citation: "JPML Rule 7.1(c)",
    description: "Deadline to file a notice of opposition to a Conditional Transfer Order (CTO). A timely opposition stops transmittal to the transferee court and triggers the Panel Clerk's 'Notice of Filed Opposition' with a briefing schedule; no response at all is treated as acquiescence.",
    triggerEvent: "CTO filed",
    days: 7,
    dayType: "calendar",
    rollForward: true,
    source: "R.P.J.P.M.L. 7.1(c) (Panel Rules eff. Feb. 19, 2026; supersedes prior Rule 6.2 numbering)",
  },
  {
    id: "jpml-6.2e",
    jurisdictionType: "jpml",
    jurisdictionLabel: "JPML — Conditional Transfer Order",
    citation: "JPML Rule 7.1(g)",
    description: "Motion to vacate the CTO, with supporting brief, due after the Panel Clerk issues the Notice of Filed Opposition (not from the party's own opposition filing). The Panel grants extensions only in exceptional circumstances.",
    triggerEvent: "Clerk's Notice of Filed Opposition issued",
    days: 14,
    dayType: "calendar",
    rollForward: true,
    source: "R.P.J.P.M.L. 7.1(g) (Panel Rules eff. Feb. 19, 2026; supersedes prior Rule 6.2 numbering)",
  },
  {
    id: "nj-46-1",
    jurisdictionType: "state",
    jurisdictionLabel: "New Jersey Superior Court",
    citation: "N.J. Ct. R. 4:6-1(a)",
    description: "Answer due after service of the summons and complaint.",
    triggerEvent: "Service of process",
    days: 35,
    dayType: "calendar",
    rollForward: true,
    source: "N.J. Ct. R. 4:6-1(a); roll-forward per R. 1:3-1",
  },
  {
    id: "nj-1-6-5",
    jurisdictionType: "state",
    jurisdictionLabel: "New Jersey Superior Court",
    citation: "N.J. Ct. R. 1:6-5",
    description: "Trial-court brief length and format: ordinary motion briefs ≤40 pages; dispositive-motion (dismiss/summary judgment) briefs ≤65 pages; reply briefs ≤15 pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "No smaller than 10-pitch or 12-point", pageLimit: "40pp motion / 65pp dispositive / 15pp reply" },
    source: "N.J. Ct. R. 1:6-5",
  },
  {
    id: "pa-1026",
    jurisdictionType: "state",
    jurisdictionLabel: "Pennsylvania (Phila. C.C.P.)",
    citation: "Pa. R. Civ. P. 1026(a)",
    description: "Responsive pleading due after service of the preceding pleading containing a notice to defend/plead (60 days if served outside the U.S.).",
    triggerEvent: "Service of process",
    days: 20,
    dayType: "calendar",
    rollForward: true,
    source: "Pa. R. Civ. P. 1026(a); computation per Pa.R.J.A. 107 (effective 2024-01-01, superseding former Pa.R.C.P. 106)",
  },
  {
    id: "ca-412-20",
    jurisdictionType: "state",
    jurisdictionLabel: "California Superior Court",
    citation: "Cal. Civ. Proc. Code § 412.20(a)(3)",
    description: "Response to complaint (answer, demurrer, or motion to strike) due after service of summons; the parties may stipulate once to a 15-day extension without a court order.",
    triggerEvent: "Service of process",
    days: 30,
    dayType: "calendar",
    rollForward: true,
    source: "Cal. Civ. Proc. Code §§ 412.20(a)(3), 430.40(a); Cal. R. Ct. 3.110(b),(d)",
  },
  {
    id: "ca-3-1113",
    jurisdictionType: "state",
    jurisdictionLabel: "California Superior Court",
    citation: "Cal. R. Ct. 3.1113(d)",
    description: "Memorandum of points and authorities length: opening/opposing memo ≤15 pages (≤20 pages for summary judgment/adjudication); reply ≤10 pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "No smaller than 12-point (Cal. R. Ct. 2.104)", pageLimit: "15pp opening/opposing (20pp MSJ) / 10pp reply" },
    source: "Cal. R. Ct. 3.1113(d), 2.104",
  },
  {
    id: "de-12a",
    jurisdictionType: "state",
    jurisdictionLabel: "Delaware Superior Court",
    citation: "Del. Super. Ct. Civ. R. 12(a)",
    description: "Answer due after service of the summons and complaint (or after appearance, if the defendant appears before service).",
    triggerEvent: "Service of process",
    days: 20,
    dayType: "calendar",
    rollForward: true,
    source: "Del. Super. Ct. Civ. R. 12(a); roll-forward per Rule 6(a)",
  },
  {
    id: "de-107",
    jurisdictionType: "state",
    jurisdictionLabel: "Delaware Superior Court",
    citation: "Del. Super. Ct. Civ. R. 107",
    description: "Brief length: opening/answering brief ≤8,000 words or ≤40 pages if not word-processed; reply brief ≤5,500 words or ≤25 pages. Rule 107 also governs Complex Commercial Litigation Division (CCLD) briefs.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "Times New Roman, 14-point, double-spaced", pageLimit: "8,000 words / 40pp opening; 5,500 words / 25pp reply" },
    source: "Del. Super. Ct. Civ. R. 107",
  },
  {
    id: "ny-3012a",
    jurisdictionType: "state",
    jurisdictionLabel: "New York Supreme Court",
    citation: "N.Y. C.P.L.R. § 3012(a)",
    description: "Answer due after service of the complaint — 20 days if served by personal delivery within New York State, 30 days for any other method (substituted service, service outside the state, etc.).",
    triggerEvent: "Service of process",
    days: 20,
    dayType: "calendar",
    rollForward: true,
    source: "N.Y. C.P.L.R. §§ 320(a), 3012(a); roll-forward per Gen. Constr. Law § 25-a",
  },
  {
    id: "ny-202-8b",
    jurisdictionType: "state",
    jurisdictionLabel: "New York Supreme Court",
    citation: "22 NYCRR § 202.8-b",
    description: "Memoranda of law length (amended eff. 2025-07-07): ≤7,000 words each for chief briefs, ≤4,200 words for reply — or ≤20 pages chief / ≤10 pages reply if not computer-generated. Commercial Division Rule 17 uses the same limits.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "No smaller than 12-point, double-spaced (22 NYCRR § 202.5(a))", pageLimit: "7,000 words / 20pp chief; 4,200 words / 10pp reply" },
    source: "22 NYCRR §§ 202.5(a), 202.8-b",
  },
  {
    id: "sdfla-7-1",
    jurisdictionType: "federal",
    jurisdictionLabel: "S.D. Fla.",
    citation: "S.D. Fla. L.R. 7.1(c)(2)",
    description: "Motion and opposition memoranda of law ≤20 pages; reply ≤10 pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "No smaller than 12-point (S.D. Fla. L.R. 5.1(a)(4))", pageLimit: "20pp motion/opposition; 10pp reply" },
    source: "S.D. Fla. L.R. 7.1(c)(2), 5.1(a)(4)",
  },
  {
    id: "ndcal-7-4",
    jurisdictionType: "federal",
    jurisdictionLabel: "N.D. Cal.",
    citation: "N.D. Cal. Civil L.R. 7-4(b)",
    description: "Opening and opposition briefs ≤25 pages; reply ≤15 pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "Proportional font e.g. Times New Roman/Century Schoolbook, ≥12-point (Civil L.R. 3-4(c)(2))", pageLimit: "25pp opening/opposition; 15pp reply" },
    source: "N.D. Cal. Civil L.R. 7-4(b), 3-4(c)(2)",
  },
  {
    id: "sdil-7-1",
    jurisdictionType: "federal",
    jurisdictionLabel: "S.D. Ill.",
    citation: "S.D. Ill. L.R. 7.1(a)(3)–(4)",
    description: "Briefs generally ≤20 double-spaced pages; reply briefs disfavored and capped at 5 pages when permitted.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "12-point", pageLimit: "20pp brief; 5pp reply" },
    source: "S.D. Ill. L.R. 7.1(a)(3)–(4)",
  },
  {
    id: "ndfla-7-1",
    jurisdictionType: "federal",
    jurisdictionLabel: "N.D. Fla.",
    citation: "N.D. Fla. L.R. 7.1(F)",
    description: "Word-count based limit: memoranda ≤8,000 words, with a mandatory certificate of word count.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "Double-spaced, ≥14-point, 1-inch margins (L.R. 5.1(C))", wordLimit: "8,000 words" },
    source: "N.D. Fla. L.R. 7.1(F), 5.1(C)",
  },
  {
    id: "edcn-7-2",
    jurisdictionType: "federal",
    jurisdictionLabel: "E.D.N.C.",
    citation: "E.D.N.C. Local Civ. R. 7.2(f)(1)–(3)",
    description: "Non-discovery motion memo ≤30 pages (or 8,400-word alternative); discovery-motion memo ≤10 pages; reply/surreply ≤10 pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "≥11-point (Local Civ. R. 10.1(b)) — font size sourced secondarily, confirm before relying on it", pageLimit: "30pp non-discovery (or 8,400 words) / 10pp discovery / 10pp reply" },
    source: "E.D.N.C. Local Civ. R. 7.2(f) (amended 2023-05-31), 10.1(b)",
  },
  {
    id: "sdny-7-1",
    jurisdictionType: "federal",
    jurisdictionLabel: "S.D.N.Y.",
    citation: "S.D.N.Y./E.D.N.Y. Local Civ. R. 7.1(c)",
    description: "Computer-prepared memoranda ≤8,750 words opening/opposition, ≤3,500 words reply (25pp/10pp if typewritten).",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "≥12-point, footnotes ≥10-point, double-spaced, 1-inch margins (Local Civ. R. 11.1(b), eff. 2026-01-02)", wordLimit: "8,750 words opening/opposition; 3,500 words reply" },
    source: "S.D.N.Y./E.D.N.Y. Local Civ. R. 7.1(c), 11.1(b)",
  },
  {
    id: "dsc-7-04",
    jurisdictionType: "federal",
    jurisdictionLabel: "D.S.C.",
    citation: "D.S.C. Local Civ. R. 7.04–7.07",
    description: "Initial memorandum ≤35 double-spaced pages; reply ≤15 double-spaced pages.",
    triggerEvent: "Motion brief filed",
    days: 0,
    dayType: "calendar",
    rollForward: false,
    formatting: { font: "Times New Roman, Arial, or Courier New, ≥12-point", pageLimit: "35pp initial memo; 15pp reply" },
    source: "D.S.C. Local Civ. R. 7.04, 7.06, 7.07",
  },
];

export function rulesForJurisdiction(jurisdictionType: JurisdictionRule["jurisdictionType"]): JurisdictionRule[] {
  return JURISDICTION_RULES.filter((r) => r.jurisdictionType === jurisdictionType);
}

/** Rules with an actual countdown (excludes filing-format-only reference entries). */
export function deadlineRulesForJurisdiction(jurisdictionType: JurisdictionRule["jurisdictionType"]): JurisdictionRule[] {
  return JURISDICTION_RULES.filter((r) => r.jurisdictionType === jurisdictionType && r.days > 0);
}

export function ruleById(id: string): JurisdictionRule | undefined {
  return JURISDICTION_RULES.find((r) => r.id === id);
}
